name : Pipeline 1

on: 
    #push:
        #branches: [main]
    workflow_dispatch:
    

jobs :
    job1:
        runs-on: ubuntu-latest 
        steps: 
            - name : step 1
              run : echo "Hello world" ${secret.SECRET}
    job2:
        runs-on: windows-latest
        needs: [job1]   
        steps:
            - name : my awesome step
              run : mkdir app
            - name : my other awesome step
              run : dir
